### ISSUE TITLE
I'm pretty sure that's a bug (but not so sure how to reproduce it)

### ISSUE THREAD

**Issue by ykurlaev** [SoltauFintel/blockpuzzle#17]
My screen was almost full with top line being empty and some empty space on the left. I had 3x3 in the stash, 3x3 and, if I remember correctly, 2x1. I removed two horizontal lines with 2x1 but the game somehow decided that I've lost. But not really lost I guess because while the field is gray I can still place pieces.
![Screenshot_2021-01-27-04-02-20-932_de mwvb blockpuzzle](https://user-images.githubusercontent.com/57290908/105906268-0dce2600-6056-11eb-9279-9398dd3c8885.jpg)
![Screenshot_2021-01-27-04-10-22-102_de mwvb blockpuzzle](https://user-images.githubusercontent.com/57290908/105906288-1292da00-6056-11eb-942d-021612473172.jpg)
![Screenshot_2021-01-27-04-10-33-597_de mwvb blockpuzzle](https://user-images.githubusercontent.com/57290908/105906303-16266100-6056-11eb-8f18-afbc3fce5033.jpg)

**Comment by SoltauFintel** [comment]
I had this bug before and fixed it. But apparently it's not working perfectly yet. Please assume that it takes about 2 weeks until an update is available.

I am assuming that you are using the latest app version of F-Droid.

The following workaround might help: Shutdown the app hard (if in doubt, restart your smartphone afterwards) and start again. The game then assesses the game situation again and it continues.

Great Score!

**Comment by SoltauFintel** [comment]
current version is still in development...

**Comment by SoltauFintel** [comment]
fixed

Version 6.0 is on Google Play
