### ISSUE TITLE
what is the one color game?

### ISSUE THREAD

**Issue by ryancastro** [SoltauFintel/blockpuzzle#22]
I've been looking through the game docs, and a little bit of the code, and I don't understand what the stone wars one color game is. Some of the games have a minimum score you have to achieve. Other games you have to achieve a score within a certain amount of moves. What does the one color game win condition due?

**Comment by SoltauFintel** [comment]
If you place 20+ blocks of the same color together they will become light blue and you get bonus score.In a one color game only this score counts. With enough score you'll win. hth

**Comment by ryancastro** [comment]
Thank you!!
