### ISSUE TITLE
More game sounds

### ISSUE THREAD

**Issue by SoltauFintel** [SoltauFintel/blockpuzzle#6]
e.g. use freesound.org

- stone dropped
- stone cannot be dropped
- parked
- Game Over Sound
- attention: New game button clicked
- more than 1 row cleared
- Gravitation

**Comment by SoltauFintel** [comment]
Done in v3.0
- game over sound
- more than 1 row cleared

**Comment by guntbert** [comment]
I want the option to have no sounds at all.

**Comment by SoltauFintel** [comment]
it's a bit hidden: Stone Wars -> bridge -> data exchange -> enter player name -> game sounds option
